# Generated by Django 6.0.4 on 2026-06-11 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='Live Stream Session', max_length=255)),
            ],
            options={
                'db_table': 'translation_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('predicted_word', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='translator.translationsession')),
            ],
            options={
                'db_table': 'translation_logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
